// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transferzor.Data;

namespace Transferzor.Migrations
{
    [DbContext(typeof(TransferzorDbContext))]
    [Migration("20200411201017_FileData")]
    partial class FileData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Transferzor.Models.FileSendData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ReceiverEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileSendData");
                });

            modelBuilder.Entity("Transferzor.Models.FileStorageData", b =>
                {
                    b.Property<int>("FileSendDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FileSendDataId")
                        .HasColumnType("int");

                    b.HasKey("FileSendDateId");

                    b.HasIndex("FileSendDataId");

                    b.ToTable("FileStorageData");
                });

            modelBuilder.Entity("Transferzor.Models.FileStorageData", b =>
                {
                    b.HasOne("Transferzor.Models.FileSendData", "FileSendData")
                        .WithMany()
                        .HasForeignKey("FileSendDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
